/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HotelsCreateRouteImport } from './routes/hotels/create'
import { Route as EventsCreateRouteImport } from './routes/events/create'
import { Route as EventsEventIdIndexRouteImport } from './routes/events/$eventId.index'
import { Route as HotelsIdEditRouteImport } from './routes/hotels/$id.edit'
import { Route as EventsEventIdEditRouteImport } from './routes/events/$eventId.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsCreateRoute = HotelsCreateRouteImport.update({
  id: '/hotels/create',
  path: '/hotels/create',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsCreateRoute = EventsCreateRouteImport.update({
  id: '/events/create',
  path: '/events/create',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdIndexRoute = EventsEventIdIndexRouteImport.update({
  id: '/events/$eventId/',
  path: '/events/$eventId/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsIdEditRoute = HotelsIdEditRouteImport.update({
  id: '/hotels/$id/edit',
  path: '/hotels/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdEditRoute = EventsEventIdEditRouteImport.update({
  id: '/events/$eventId/edit',
  path: '/events/$eventId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/events/create': typeof EventsCreateRoute
  '/hotels/create': typeof HotelsCreateRoute
  '/events/$eventId/edit': typeof EventsEventIdEditRoute
  '/hotels/$id/edit': typeof HotelsIdEditRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/events/create': typeof EventsCreateRoute
  '/hotels/create': typeof HotelsCreateRoute
  '/events/$eventId/edit': typeof EventsEventIdEditRoute
  '/hotels/$id/edit': typeof HotelsIdEditRoute
  '/events/$eventId': typeof EventsEventIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/events/create': typeof EventsCreateRoute
  '/hotels/create': typeof HotelsCreateRoute
  '/events/$eventId/edit': typeof EventsEventIdEditRoute
  '/hotels/$id/edit': typeof HotelsIdEditRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/events/create'
    | '/hotels/create'
    | '/events/$eventId/edit'
    | '/hotels/$id/edit'
    | '/events/$eventId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/events/create'
    | '/hotels/create'
    | '/events/$eventId/edit'
    | '/hotels/$id/edit'
    | '/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/events/create'
    | '/hotels/create'
    | '/events/$eventId/edit'
    | '/hotels/$id/edit'
    | '/events/$eventId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  EventsCreateRoute: typeof EventsCreateRoute
  HotelsCreateRoute: typeof HotelsCreateRoute
  EventsEventIdEditRoute: typeof EventsEventIdEditRoute
  HotelsIdEditRoute: typeof HotelsIdEditRoute
  EventsEventIdIndexRoute: typeof EventsEventIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/create': {
      id: '/hotels/create'
      path: '/hotels/create'
      fullPath: '/hotels/create'
      preLoaderRoute: typeof HotelsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/create': {
      id: '/events/create'
      path: '/events/create'
      fullPath: '/events/create'
      preLoaderRoute: typeof EventsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/': {
      id: '/events/$eventId/'
      path: '/events/$eventId'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof EventsEventIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/$id/edit': {
      id: '/hotels/$id/edit'
      path: '/hotels/$id/edit'
      fullPath: '/hotels/$id/edit'
      preLoaderRoute: typeof HotelsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/edit': {
      id: '/events/$eventId/edit'
      path: '/events/$eventId/edit'
      fullPath: '/events/$eventId/edit'
      preLoaderRoute: typeof EventsEventIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  EventsCreateRoute: EventsCreateRoute,
  HotelsCreateRoute: HotelsCreateRoute,
  EventsEventIdEditRoute: EventsEventIdEditRoute,
  HotelsIdEditRoute: HotelsIdEditRoute,
  EventsEventIdIndexRoute: EventsEventIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
